
<h1>Weather</h1>
<div class="row">
    <div class="col-md-5 col-sm-5 col-xs-12">
        <label for="sel1">Wpisz miasto dla którego chcesz wyświetlić aktualną prognozę pogody...</label>
        <div class="search">
            <input class="form-control" id="input-search-weather" type="text" placeholder="Szukaj miasta...">
            <button id="btn-search-weather" type="button" class="btn btn-default">Szukaj</button>
        </div>
    </div>
    <div class="col-xs-12">
        <div id="gmap"></div>   
    </div>
</div>