
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />
    <link rel="stylesheet" href="css/style.css">
</head>
<body class="home">
<div class="container-fluid display-table">
    <div class="row display-table-row">
        <div class="col-md-2 col-sm-1 hidden-xs display-table-cell v-align box" id="navigation">
            <div class="logo">
                <a href="index.html"> UP-DASHBOARD 2017
                    <!--<img src="" alt="merkery_logo" class="hidden-xs hidden-sm">
                    <img src="" alt="merkery_logo" class="visible-xs visible-sm circle-logo">-->
                </a>
            </div>
            <div class="navi">
                <ul>
                    <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Home</span></a></li>
                    <li><a href="/twitter"><i class="fa fa-twitter" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Twitter</span></a></li>
                    <li><a href="#"><i class="fa fa-youtube-play" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Youtube</span></a></li>
                    <li><a href="/weather"><i class="fa fa-cloud" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Weather</span></a></li>
                    <li><a href="/googlemaps"><i class="fa fa-map-marker" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Google maps</span></a></li>
                    <li><a href="/spotify"><i class="fa fa-spotify" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Spotify</span></a></li>
                    <li><a href="#"><i class="fa fa-cog" aria-hidden="true"></i><span class="hidden-xs hidden-sm">Setting</span></a></li>
                </ul>
            </div>
        </div>
        <div class="col-md-10 col-sm-11 display-table-cell v-align">
            <div class="row">
                <header>
                    <div class="col-md-7">
                        <nav class="navbar-default pull-left">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle collapsed" data-toggle="offcanvas" data-target="#side-menu" aria-expanded="false">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                        </nav>
                        <!--<div class="search hidden-xs hidden-sm">
                          <input type="text" placeholder="Search" id="search">
                        </div>-->
                    </div>
                    <div class="col-md-5">
                        <!--<div class="header-rightside">
                          <ul class="list-inline header-top pull-right">
                            <li class="hidden-xs"><a href="#" class="add-project" data-toggle="modal" data-target="#add_project">Add Project</a></li>
                            <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i></a></li>
                            <li>
                              <a href="#" class="icon-info">
                              <i class="fa fa-bell" aria-hidden="true"></i>
                              <span class="label label-primary">3</span>
                              </a>
                            </li>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="" alt="user">
                              <b class="caret"></b></a>
                              <ul class="dropdown-menu">
                                <li>
                                  <div class="navbar-content">
                                    <span>JS Krishna</span>
                                    <p class="text-muted small">
                                      me@jskrishna.com
                                    </p>
                                    <div class="divider">
                                    </div>
                                    <a href="#" class="view btn-sm active">View Profile</a>
                                  </div>
                                </li>
                              </ul>
                            </li>
                          </ul>
                        </div>-->
                    </div>
                </header>
            </div>
            <div class="user-dashboard">
<?php
//tutaj includujemy content szablonu!!!
include ($template);
?>

                <!--<div class="row">
                  <div class="col-md-5 col-sm-5 col-xs-12 gutter">
                    <div class="sales">
                      <h2>Your Sale</h2>
                      <div class="btn-group">
                        <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span>Period:</span> Last Year
                        </button>
                        <div class="dropdown-menu">
                          <a href="#">2012</a>
                          <a href="#">2014</a>
                          <a href="#">2015</a>
                          <a href="#">2016</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="col-md-7 col-sm-7 col-xs-12 gutter">
                    <div class="sales report">
                      <h2>Report</h2>
                      <div class="btn-group">
                        <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span>Period:</span> Last Year
                        </button>
                        <div class="dropdown-menu">
                          <a href="#">2012</a>
                          <a href="#">2014</a>
                          <a href="#">2015</a>
                          <a href="#">2016</a>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>-->
            </div>
        </div>
    </div>
</div>
<div id="add_project" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header login-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h4 class="modal-title">Add Project</h4>
            </div>
            <div class="modal-body">
                <input type="text" placeholder="Project Title" name="name">
                <input type="text" placeholder="Post of Post" name="mail">
                <input type="text" placeholder="Author" name="passsword">
                <textarea placeholder="Desicrption"></textarea>
            </div>
            <div class="modal-footer">
                <button type="button" class="cancel" data-dismiss="modal">Close</button>
                <button type="button" class="add-project" data-dismiss="modal">Save</button>
            </div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="js/jsrender.js"></script>
<script src="js/main.js"></script>
<script src="js/twitter.js"></script>
<script src="js/googlemaps.js"></script>
<script src="js/spotify.js"></script>
</body>
</html>

