
<h1>Google maps</h1>
<div class="row">
    <div class="col-md-5 col-sm-5 col-xs-12">
        <span>Wpisz fraze ktora chcesz wyszukac w google maps</span>
        <div class="search">
            <input id="input-search-google" type="text" placeholder="Szukaj slowa..." class="form-control">
            <button id="btn-search-google" type="button" class="btn btn-default">Szukaj</button>
        </div>
    </div>
    <div class="col-xs-12">
        <div id="gmap"></div>   
    </div>
</div>