
<h1>Twitter</h1>
<div class="row">
    <div class="col-md-5 col-sm-5 col-xs-12">
        <span>Wpisz fraze ktora chcesz wyszukac na twiterze...</span>
        <div class="search">
            <input id="input-search" type="text" placeholder="Szukaj slowa..." id="search">
            <button id="btn-search" type="button" class="btn btn-default">Search</button>
        </div>
    </div>
    <div class="col-xs-12">
        <ul id="searchResults">
        </ul>
    </div>
</div>