
<h1>Twitter</h1>
<div class="row">
    <div class="col-md-5 col-sm-5 col-xs-12">
        <label for="sel1">Wpisz fraze ktora chcesz wyszukac na twiterze...</label>
        <div class="search">
            <input class="form-control" id="input-search" type="text" placeholder="Szukaj slowa..." id="search">
            <div class="form-group">
                <label for="sel1">Liczba tweetów:</label>
                <select name="tweets" class="form-control" id="sel1">
                    <option>5</option>
                    <option>10</option>
                    <option>15</option>
                </select>
            </div>
            <button id="btn-search" type="button" class="btn btn-default">Search</button>

        </div>
    </div>
    <div class="col-xs-12">
        <div style="display:none;     padding: 122px;" id="preloader"><img src="cat_preloader.gif"/></div>

        <div id="searchResults">

        </div>
    </div>
</div>